### ISSUE TITLE
Rush Hour in 2P

### ISSUE THREAD

**Issue by helios2** [Androidiani/Sensor-Pong#2]
Crash durante Rush Hour in 2P

Log:
04-07 17:12:46.917  24183-24455/it.unina.is2project.sensorgames E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 3297
    java.lang.IndexOutOfBoundsException: Invalid index 7, size is 5
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
            at java.util.ArrayList.get(ArrayList.java:304)
            at org.andengine.entity.Entity.onManagedDraw(Entity.java:1382)
            at org.andengine.entity.scene.Scene.onManagedDraw(Scene.java:260)
            at org.andengine.entity.Entity.onDraw(Entity.java:1160)
            at org.andengine.engine.Engine.onDrawScene(Engine.java:627)
            at org.andengine.engine.Engine.onDrawFrame(Engine.java:617)
            at org.andengine.opengl.view.EngineRenderer.onDrawFrame(EngineRenderer.java:105)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1462)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)

**Comment by alessandro-gargiulo** [comment]
04-13 11:13:06.708  18822-19322/it.unina.is2project.sensorgames D/BonusManager﹕ Remain 0 of ID: 9
04-13 11:13:06.708  18822-19322/it.unina.is2project.sensorgames D/BonusManager﹕ Removed bonus ID: 9
04-13 11:13:06.723  18822-18822/it.unina.is2project.sensorgames D/BONUSEXPIRED﹕ RUSHHOUR
04-13 11:13:06.794  18822-19323/it.unina.is2project.sensorgames E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 1310
    Process: it.unina.is2project.sensorgames, PID: 18822
    java.lang.IndexOutOfBoundsException: Invalid index 29, size is 29
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at org.andengine.entity.Entity.onManagedDraw(Entity.java:1382)
            at org.andengine.entity.scene.Scene.onManagedDraw(Scene.java:260)
            at org.andengine.entity.Entity.onDraw(Entity.java:1160)
            at org.andengine.engine.Engine.onDrawScene(Engine.java:627)
            at org.andengine.engine.Engine.onDrawFrame(Engine.java:617)
            at org.andengine.opengl.view.EngineRenderer.onDrawFrame(EngineRenderer.java:105)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
