### ISSUE TITLE
Open Activity Stats On Nexus 7

### ISSUE THREAD

**Issue by alessandro-gargiulo** [Androidiani/Sensor-Pong#3]
CRASH LOG:
04-12 12:48:25.730    3788-3788/it.unina.is2project.sensorgames E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: it.unina.is2project.sensorgames, PID: 3788
    java.lang.RuntimeException: Unable to start activity ComponentInfo{it.unina.is2project.sensorgames/it.unina.is2project.sensorgames.stats.activity.StatsActivity}: android.database.sqlite.SQLiteException: no such table: stat_one_player (code 1): , while compiling: SELECT id, score, data, id_player FROM stat_one_player ORDER BY score DESC
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: android.database.sqlite.SQLiteException: no such table: stat_one_player (code 1): , while compiling: SELECT id, score, data, id_player FROM stat_one_player ORDER BY score DESC
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
            at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
            at it.unina.is2project.sensorgames.stats.database.dao.StatOnePlayerDAO.findAll(StatOnePlayerDAO.java:120)
            at it.unina.is2project.sensorgames.stats.service.StatService.getStatOnePlayerList(StatService.java:31)
            at it.unina.is2project.sensorgames.stats.activity.StatsActivity.onCreate(StatsActivity.java:66)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by alessandro-gargiulo** [comment]
Disinstallato e reinstallato l'app. Non crasha più però il menù a tendina si vede sempre in modo strano.
